# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wh5JupO_7LYfWn94zHf8mppiHkgJ-eud
"""

!pip install git+https://github.com/huggingface/diffusers.git
import shutil
shutil.move("./safety_checker.py", "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/deepfloyd_if/safety_checker.py")